steps:
  # Build and push with secrets (all in one step)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔐 Retrieving secrets from Secret Manager..."
        CLERK_PUB_KEY=$(gcloud secrets versions access latest --secret="clerk-publishable-key")
        CLERK_SECRET_KEY=$(gcloud secrets versions access latest --secret="clerk-secret-key")
        PAYSTACK_PUB_KEY=$(gcloud secrets versions access latest --secret="paystack-public-key")
        PAYSTACK_SECRET_KEY=$(gcloud secrets versions access latest --secret="paystack-secret-key")
        GOOGLE_MAPS_KEY=$(gcloud secrets versions access latest --secret="google-maps-api-key")

        echo "🏗️ Building Docker image with secrets..."
        docker build \
          --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="$$CLERK_PUB_KEY" \
          --build-arg CLERK_SECRET_KEY="$$CLERK_SECRET_KEY" \
          --build-arg NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY="$$PAYSTACK_PUB_KEY" \
          --build-arg PAYSTACK_SECRET_KEY="$$PAYSTACK_SECRET_KEY" \
          --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY="$$GOOGLE_MAPS_KEY" \
          -t gcr.io/$PROJECT_ID/rides-app .

        echo "🚀 Pushing Docker image..."
        docker push gcr.io/$PROJECT_ID/rides-app

images:
  - 'gcr.io/$PROJECT_ID/rides-app'