steps:
  # Create .env.local file from secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating .env.local file from secrets..."
        echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$(gcloud secrets versions access latest --secret=clerk-publishable-key)" > .env.local
        echo "CLERK_SECRET_KEY=$(gcloud secrets versions access latest --secret=clerk-secret-key)" >> .env.local
        echo "NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=$(gcloud secrets versions access latest --secret=paystack-public-key)" >> .env.local
        echo "PAYSTACK_SECRET_KEY=$(gcloud secrets versions access latest --secret=paystack-secret-key)" >> .env.local
        echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$(gcloud secrets versions access latest --secret=google-maps-api-key)" >> .env.local
        echo ".env.local created successfully"

  # Build Docker image with .env.local file
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rides-app', '.']

images:
  - 'gcr.io/$PROJECT_ID/rides-app'