services:
  postgres:
    image: postgres:15-alpine
    container_name: naija-rides-postgres
    environment:
      POSTGRES_DB: rides_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rides_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: